# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopping.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshopping.proto\x12\x08shopping\"4\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\titem_name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"5\n\x11\x43reateItemRequest\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\"6\n\x12\x43reateItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\x0fReadItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x10ReadItemResponse\x12\x1c\n\x04item\x18\x01 \x01(\x0b\x32\x0e.shopping.Item\"A\n\x11UpdateItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\titem_name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"6\n\x12UpdateItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x11\x44\x65leteItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"6\n\x12\x44\x65leteItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xaf\x02\n\x0fShoppingService\x12G\n\nCreateItem\x12\x1b.shopping.CreateItemRequest\x1a\x1c.shopping.CreateItemResponse\x12\x41\n\x08ReadItem\x12\x19.shopping.ReadItemRequest\x1a\x1a.shopping.ReadItemResponse\x12G\n\nUpdateItem\x12\x1b.shopping.UpdateItemRequest\x1a\x1c.shopping.UpdateItemResponse\x12G\n\nDeleteItem\x12\x1b.shopping.DeleteItemRequest\x1a\x1c.shopping.DeleteItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shopping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=28
  _globals['_ITEM']._serialized_end=80
  _globals['_CREATEITEMREQUEST']._serialized_start=82
  _globals['_CREATEITEMREQUEST']._serialized_end=135
  _globals['_CREATEITEMRESPONSE']._serialized_start=137
  _globals['_CREATEITEMRESPONSE']._serialized_end=191
  _globals['_READITEMREQUEST']._serialized_start=193
  _globals['_READITEMREQUEST']._serialized_end=222
  _globals['_READITEMRESPONSE']._serialized_start=224
  _globals['_READITEMRESPONSE']._serialized_end=272
  _globals['_UPDATEITEMREQUEST']._serialized_start=274
  _globals['_UPDATEITEMREQUEST']._serialized_end=339
  _globals['_UPDATEITEMRESPONSE']._serialized_start=341
  _globals['_UPDATEITEMRESPONSE']._serialized_end=395
  _globals['_DELETEITEMREQUEST']._serialized_start=397
  _globals['_DELETEITEMREQUEST']._serialized_end=428
  _globals['_DELETEITEMRESPONSE']._serialized_start=430
  _globals['_DELETEITEMRESPONSE']._serialized_end=484
  _globals['_SHOPPINGSERVICE']._serialized_start=487
  _globals['_SHOPPINGSERVICE']._serialized_end=790
# @@protoc_insertion_point(module_scope)
